#!/usr/bin/env python3
"""Bundle the prepared corpora for the rented GPU machine.

    python cloud/pack_data.py --out D:/archcad_cloud_data            # on the development machine
    # upload the folder (credentials from the environment only), e.g.
    #   aws s3 sync D:/archcad_cloud_data s3://<bucket>/archcad/data/
    # on the GPU machine, from the repository root:
    #   aws s3 sync s3://<bucket>/archcad/data/ cloud_data/ && bash cloud_data/unpack.sh

Bundles (only those present):
  us_lines.tar.gz           dataset/us_plans/lines        (US plan windows, Arch-43, text, layer names)
  cubicasa_lines.tar.gz     dataset/cubicasa5k/lines_*    (CubiCasa5K line JSONs, both label spaces)
  floorplancad_v2/*.archive the FloorPlanCAD-V2 release archives as downloaded (xz tars of SVG + PNG)
plus MANIFEST.json (sizes, sha256) and unpack.sh, which verifies and extracts into
the paths the configs use.
"""
import argparse
import hashlib
import json
import os
import os.path as osp
import shutil
import tarfile

ROOT = osp.dirname(osp.dirname(osp.abspath(__file__)))


def sha256(path, chunk=1 << 22):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(chunk), b""):
            h.update(block)
    return h.hexdigest()


def tar_dirs(out_path, dirs):
    with tarfile.open(out_path, "w:gz", compresslevel=3) as tar:
        for d in dirs:
            tar.add(osp.join(ROOT, d), arcname=d.replace(os.sep, "/"))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", required=True)
    ap.add_argument("--skip", nargs="*", default=[], choices=["us", "cubicasa", "fpcad"])
    a = ap.parse_args()
    os.makedirs(a.out, exist_ok=True)
    manifest, unpack = {}, ["#!/usr/bin/env bash", "# generated by cloud/pack_data.py; run from the repository root",
                            "set -euo pipefail", 'D=$(cd "$(dirname "$0")" && pwd)',
                            '(cd "$D" && sha256sum -c SHA256SUMS)']

    if "us" not in a.skip and osp.isdir(osp.join(ROOT, "dataset/us_plans/lines")):
        tar_dirs(osp.join(a.out, "us_lines.tar.gz"), ["dataset/us_plans/lines"])
        manifest["us_lines.tar.gz"] = "dataset/us_plans/lines"
        unpack.append('tar -xzf "$D/us_lines.tar.gz" -C .')
    cc = [d for d in ("dataset/cubicasa5k/lines_arch43", "dataset/cubicasa5k/lines_cubicasa12")
          if osp.isdir(osp.join(ROOT, d))]
    if "cubicasa" not in a.skip and cc:
        tar_dirs(osp.join(a.out, "cubicasa_lines.tar.gz"), cc)
        manifest["cubicasa_lines.tar.gz"] = ", ".join(cc)
        unpack.append('tar -xzf "$D/cubicasa_lines.tar.gz" -C .')
    if "fpcad" not in a.skip:
        os.makedirs(osp.join(a.out, "floorplancad_v2"), exist_ok=True)
        for part in ("train_1", "train_2", "test"):
            src = osp.join(ROOT, "dataset/FloorplanCAD", part + ".archive")
            if osp.isfile(src):
                shutil.copy2(src, osp.join(a.out, "floorplancad_v2", part + ".archive"))
                manifest[f"floorplancad_v2/{part}.archive"] = f"vecformer/datasets/FloorPlanCAD-V2/{part}"
                unpack.append(f'mkdir -p vecformer/datasets/FloorPlanCAD-V2/{part} && '
                              f'tar -xJf "$D/floorplancad_v2/{part}.archive" -C vecformer/datasets/FloorPlanCAD-V2/{part}')

    sums = []
    for name in manifest:
        path = osp.join(a.out, name)
        digest = sha256(path)
        sums.append(f"{digest}  {name}")
        manifest[name] = dict(extracts_to=manifest[name], bytes=osp.getsize(path), sha256=digest)
        print(f"{name}: {osp.getsize(path) / 1e9:.2f} GB")
    with open(osp.join(a.out, "SHA256SUMS"), "w", newline="\n") as f:
        f.write("\n".join(sums) + "\n")
    with open(osp.join(a.out, "MANIFEST.json"), "w") as f:
        json.dump(manifest, f, indent=1)
    unpack.append('echo "unpacked: see MANIFEST.json"')
    with open(osp.join(a.out, "unpack.sh"), "w", newline="\n") as f:
        f.write("\n".join(unpack) + "\n")
    print("wrote", a.out)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
